default:
  adapter: postgresql
  host: localhost
development:
  adapter: postgresql
  host: localhost
  datamapper_adapter: postgres
  database: redcap2omop_development
  username: redcap2omop_development
  password: redcap2omop_development
test:
  adapter: postgresql
  host: localhost
  datamapper_adapter: postgres
  database: redcap2omop_test
  username: redcap2omop_test
  password: redcap2omop_test
