class RedcapVariableChoiceMap < ApplicationRecord
  belongs_to :redcap_variable_choice

  REDCAP_VARIABLE_CHOICE_MAP_MAP_TYPE_OMOP_COLUMN = 'OMOP column'
  REDCAP_VARIABLE_CHOICE_MAP_MAP_TYPE_OMOP_CONCEPT = 'OMOP concept'
  REDCAP_VARIABLE_CHOICE_MAP_MAP_TYPES = [REDCAP_VARIABLE_CHOICE_MAP_MAP_TYPE_OMOP_COLUMN, REDCAP_VARIABLE_CHOICE_MAP_MAP_TYPE_OMOP_CONCEPT]
end